server:
  port: 8080
logging:
  level:
    liquibase.executor.jvm.JdbcExecutor: ERROR

spring:
  application:
    name: telegram-bot-dorian
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/postgres}?ApplicationName=${spring.application.name}
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
